## Clock
#set_property PACKAGE_PIN E3    [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#create_clock -period 10.000 -name clk [get_ports clk]

## Buttons
#set_property PACKAGE_PIN N17   [get_ports reset]
#set_property IOSTANDARD LVCMOS33 [get_ports reset]
#set_property PACKAGE_PIN M18   [get_ports cancel]
#set_property IOSTANDARD LVCMOS33 [get_ports cancel]

## Switches (coin and select)
#set_property PACKAGE_PIN J15   [get_ports {coin[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {coin[0]}]
#set_property PACKAGE_PIN L16   [get_ports {coin[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {coin[1]}]
#set_property PACKAGE_PIN M13   [get_ports {select[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {select[0]}]
#set_property PACKAGE_PIN R15   [get_ports {select[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {select[1]}]

## LEDs
#set_property PACKAGE_PIN H17   [get_ports product_a]
#set_property IOSTANDARD LVCMOS33 [get_ports product_a]
#set_property PACKAGE_PIN K15   [get_ports product_b]
#set_property IOSTANDARD LVCMOS33 [get_ports product_b]
#set_property PACKAGE_PIN J13   [get_ports product_c]
#set_property IOSTANDARD LVCMOS33 [get_ports product_c]
#set_property PACKAGE_PIN N14   [get_ports {change[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {change[0]}]
#set_property PACKAGE_PIN R18   [get_ports {change[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {change[1]}]

## 7‑segment cathodes
#set_property PACKAGE_PIN T10   [get_ports {cathode[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
#set_property PACKAGE_PIN R10   [get_ports {cathode[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
#set_property PACKAGE_PIN K16   [get_ports {cathode[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
#set_property PACKAGE_PIN K13   [get_ports {cathode[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
#set_property PACKAGE_PIN P15   [get_ports {cathode[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
#set_property PACKAGE_PIN T11   [get_ports {cathode[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
#set_property PACKAGE_PIN L18   [get_ports {cathode[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]

## 7‑segment anodes
#set_property PACKAGE_PIN J17   [get_ports {anode[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
#set_property PACKAGE_PIN J18   [get_ports {anode[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
#set_property PACKAGE_PIN T9    [get_ports {anode[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
#set_property PACKAGE_PIN J14   [get_ports {anode[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
#set_property PACKAGE_PIN P14   [get_ports {anode[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anode[4]}]
#set_property PACKAGE_PIN T14   [get_ports {anode[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anode[5]}]
#set_property PACKAGE_PIN K2    [get_ports {anode[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anode[6]}]
#set_property PACKAGE_PIN U13   [get_ports {anode[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {anode[7]}]


# Clock
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name clk [get_ports clk]

# Buttons
set_property PACKAGE_PIN N17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN M18 [get_ports cancel]
set_property IOSTANDARD LVCMOS33 [get_ports cancel]

# Switches - coin[1:0] on SW0, SW1
set_property PACKAGE_PIN J15 [get_ports {coin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {coin[0]}]
set_property PACKAGE_PIN L16 [get_ports {coin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {coin[1]}]

# Switches - select[2:0] on SW2, SW3, SW4
set_property PACKAGE_PIN M13 [get_ports {select[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[0]}]
set_property PACKAGE_PIN R15 [get_ports {select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[1]}]
set_property PACKAGE_PIN R17 [get_ports {select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[2]}]

# LEDs - product[6:0] on LD0..LD6
set_property PACKAGE_PIN H17 [get_ports {product[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {product[0]}]
set_property PACKAGE_PIN K15 [get_ports {product[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {product[1]}]
set_property PACKAGE_PIN J13 [get_ports {product[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {product[2]}]
set_property PACKAGE_PIN N14 [get_ports {product[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {product[3]}]
set_property PACKAGE_PIN R18 [get_ports {product[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {product[4]}]
set_property PACKAGE_PIN V17 [get_ports {product[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {product[5]}]
set_property PACKAGE_PIN U17 [get_ports {product[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {product[6]}]

# LEDs - change[5:0] on LD7..LD12
set_property PACKAGE_PIN U16 [get_ports {change[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {change[0]}]
set_property PACKAGE_PIN V16 [get_ports {change[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {change[1]}]
set_property PACKAGE_PIN T15 [get_ports {change[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {change[2]}]
set_property PACKAGE_PIN U14 [get_ports {change[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {change[3]}]
set_property PACKAGE_PIN T16 [get_ports {change[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {change[4]}]
set_property PACKAGE_PIN V15 [get_ports {change[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {change[5]}]

# 7-segment display - Cathodes
set_property PACKAGE_PIN T10 [get_ports {cathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
set_property PACKAGE_PIN R10 [get_ports {cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property PACKAGE_PIN K16 [get_ports {cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property PACKAGE_PIN K13 [get_ports {cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property PACKAGE_PIN P15 [get_ports {cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property PACKAGE_PIN T11 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property PACKAGE_PIN L18 [get_ports {cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]

# 7-segment display - Anodes
set_property PACKAGE_PIN J17 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN J18 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN T9 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN J14 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property PACKAGE_PIN P14 [get_ports {anode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[4]}]
set_property PACKAGE_PIN T14 [get_ports {anode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[5]}]
set_property PACKAGE_PIN K2 [get_ports {anode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[6]}]
set_property PACKAGE_PIN U13 [get_ports {anode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[7]}]
